# 서버 포트
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    use-relative-redirects: true

# Spring 설정
spring:
  servlet:
    multipart:
      #max-file-size: 2GB
      #max-request-size: 2GB
      max-file-size: 500MB
      max-request-size: 500MB
  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/video?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    #password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  security:
    user:
      name: admin
      password: admin

  #JPA 설정
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true       # SQL 출력
        format_sql: true     # SQL 포맷팅
        use_sql_comments: true # SQL 주석 표시
    hibernate:
      #ddl-auto: update       # 테이블 생성 전략
      ddl-auto: create       # 테이블 생성 전략

# 파일 경로 설정
file:
  upload:
    #LocalMac
    #video-path: /Users/jeongminsig/coding/Java/uploads/videos/
    #thumbnail-path: /Users/jeongminsig/coding/Java/uploads/thumbnails/

    #LocalWindows
    #video-path: C:/coding/Java project/uploads/videos/
    #thumbnail-path: C:/coding/Java project/uploads/thumbnails/

    video-path: /tmp/uploads/videos/
    thumbnail-path: /tmp/uploads/thumbnails/