# 서버 포트
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    use-relative-redirects: true

# Spring 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  security:
    user:
      name: admin
      password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true       # SQL 출력
        format_sql: true     # SQL 포맷팅
        use_sql_comments: true # SQL 주석 표시
    hibernate:
      ddl-auto: update       # 테이블 생성 전략
